### ISSUE TITLE
.NET/C# build insights support

### ISSUE THREAD

**Issue by awakecoding** [microsoft/vcperf#22]
I am trying to diagnose very slow build times in a large C# project (VBCSCompiler.exe pegging the CPU for ~90s after a one-liner change, every time). I would love to use WPA to diagnose what can cause this extreme CPU usage on every build when so little code has changed. Is there an equivalent of this but for C# projects instead of C++?

**Comment by helena-gregg** [comment]
No, there is not currently an equivalent for C#.

**Comment by helena-gregg** [comment]
Please open a suggestion here: [https://developercommunity.visualstudio.com/](https://developercommunity.visualstudio.com/)
