### ISSUE TITLE
Readme.md does not say how to provide a session name

### ISSUE THREAD

**Issue by ScottHutchinson** [microsoft/vcperf#6]
The command line interface says that /start "Tells vcperf.exe to start a trace under the given session name.", but it does not say how to provide a session name.

Please add at least one or two examples of a complete command line.

Also, I think the solution will not build using VS 2017, so the instructions should say to open it in VS 2019.

Thanks

**Comment by kevcadieux** [comment]
Hi Scott,

Thanks for reporting the issue with the README. This will be fixed soon.
It's possible to build vcperf with VS 2017 if retargeting the project to use the v141 toolset and a different version of the Windows 10 SDK (whichever one is available on your PC).
I will add notes to this effect in the documentation as well.
