### ISSUE TITLE
cant stop vperf

### ISSUE THREAD

**Issue by jmecosta** [microsoft/vcperf#9]
hi,

how to force stop session?

e:\test>D:\prod\structures\MSBuild\..\Packages\vcperf.1.0.0\build\vcperf.exe /stop VPERFMSBUILDTASK asasda.etl
Microsoft (R) Visual C++ (R) Performance Analyzer DEVELOPER VERSION
Stopping tracing session VPERFMSBUILDTASK...
Dropped MSVC events: 0
Dropped MSVC buffers: 0
Dropped system events: 0
Dropped system buffers: 0
Failed to stop trace.
ERROR CODE: FAILURE_SESSION_DIRECTORY_RESOLUTION

tried /stop /stopnoanalyse 

Logger Name:            MSVC_BUILD_INSIGHTS_SESSION_VPERFMSBUILDTASK
Logger Id:              0x1d
Logger Thread Id:       0000B070
Guid:                   f6918e25-9dae-11ea-af58-54bf6479e167
Session Security:       D:(A;;0x1800;;;WD)(A;;0x120fff;;;SY)(A;;0x120fff;;;LS)(A;;0x120fff;;;NS)(A;;0x120fff;;;BA)(A;;0xee5;;;LU)(A;;LC;;;MU)(A;;0x1800;;;AC)(A;;0x1800;;;S-1-15-3-1024-3153509613-960666767-3724611135-2725662640-12138253-543910227-1950414635-4190290187)
Buffer Size:            256 Kb
Maximum Buffers:        320
Minimum Buffers:        64
Number of Buffers:      64
Free Buffers:           48
Buffers Written:        37
Events Lost:            0
Log Buffers Lost:       0
Real Time Buffers Lost: 0
Real Time Consumers:    0
ClockType:              PerfCounter
Log Mode:               Sequential 
Hybrid Shutdown:        Stop
Maximum File Size:      not set
Buffer Flush Timer:     not set
Log Filename:           C:\Users\jocs\AppData\Local\Temp\CppBuildInsights\{104BA2FC-DF47-4DCF-BDF1-EC440C8B0565}\msvc.etl

**Comment by kevcadieux** [comment]
Hi Jorge, try the following 2 commands:

xperf -stop
xperf -stop "MSVC_BUILD_INSIGHTS_SESSION_VPERFMSBUILDTASK"

Please let me know if you are still having issues.

**Comment by jmecosta** [comment]
Thanks for the quick aswer, i will close this once i verify it. I was
following the instructions that vcperf provides, matbe xperf could be added
there also. Ive use the trace application but that failed, so ive send a
restart command to the machine but the machine did not come up. So need to
wait for tommorrow

**Comment by jmecosta** [comment]
i will reopen if i this happens again. thanks for the help
